/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

/**
 *
 * @author 2830482311021
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public FrmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnbMenu = new javax.swing.JMenuBar();
        mnuArquivo = new javax.swing.JMenu();
        itmSair = new javax.swing.JMenuItem();
        mnuSobre = new javax.swing.JMenu();
        mnuAplicações = new javax.swing.JMenu();
        itmCliente = new javax.swing.JMenuItem();
        itmProduto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuArquivo.setText("Cadastro");

        itmSair.setText("Sair");
        mnuArquivo.add(itmSair);

        mnbMenu.add(mnuArquivo);

        mnuSobre.setText("Sobre");
        mnbMenu.add(mnuSobre);

        mnuAplicações.setText("Aplicações");

        itmCliente.setText("Cliente");
        itmCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmClienteActionPerformed(evt);
            }
        });
        mnuAplicações.add(itmCliente);

        itmProduto.setText("Produto");
        itmProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmProdutoActionPerformed(evt);
            }
        });
        mnuAplicações.add(itmProduto);

        mnbMenu.add(mnuAplicações);

        setJMenuBar(mnbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmClienteActionPerformed
        FrmCliente cliente = new FrmCliente();
        
        cliente.setVisible(true);
    }//GEN-LAST:event_itmClienteActionPerformed

    private void itmProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmProdutoActionPerformed
        FrmProduto produto = new FrmProduto();
        
        produto.setVisible(true);
    }//GEN-LAST:event_itmProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmCliente;
    private javax.swing.JMenuItem itmProduto;
    private javax.swing.JMenuItem itmSair;
    private javax.swing.JMenuBar mnbMenu;
    private javax.swing.JMenu mnuAplicações;
    private javax.swing.JMenu mnuArquivo;
    private javax.swing.JMenu mnuSobre;
    // End of variables declaration//GEN-END:variables
}
